import { CFormCheck, CButton } from "@coreui/react"

export const userData = [
    { id: 1, name: 'Samppa Nori', registered: '1@example.com', role: '96523', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 2, name: 'Estavan Lykos', registered: '1@example.com', role: '45664', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 3, name: 'Chetan Mohamed', registered: '1@example.com', role: '456456', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 4, name: 'Derick Maximinus', registered: '1@example.com', role: '456456', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 5, name: 'Friderik Dávid', registered: '1@example.com', role: '4564456', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 6, name: 'Yiorgos Avraamu', registered: '1@example.com', role: '456456', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 7, name: 'Avram Tarasios', registered: '1@example.com', role: '45645', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 8, name: 'Quintin Ed', registered: '1@example.com', role: '45645', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 9, name: 'Enéas Kwadwo', registered: '1@example.com', role: '7862', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 10, name: 'Agapetus Tadeáš', registered: '1@example.com', role: '778378', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 11, name: 'Carwyn Fachtna', registered: '1@example.com', role: '73783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 12, name: 'Nehemiah Tatius', registered: '1@example.com', role: '7837783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 13, name: 'Ebbe Gemariah', registered: '1@example.com', role: '783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 14, name: 'Eustorgios Amulius', registered: '1@example.com', role: '73783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 15, name: 'Leopold Gáspár', registered: '1@example.com', role: '7833', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 16, name: 'Pompeius René', registered: '1@example.com', role: '783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 17, name: 'Paĉjo Jadon', registered: '1@example.com', role: '783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 18, name: 'Micheal Mercurius', registered: '1@example.com', role: '783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 19, name: 'Ganesha Dubhghall', registered: '1@example.com', role: '783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 20, name: 'Hiroto Šimun', registered: '1@example.com', role: '45378', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 21, name: 'Vishnu Serghei', registered: '1@example.com', role: '3378378', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 22, name: 'Zbyněk Phoibos', registered: '1@example.com', role: '783783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 23, name: 'Aulus Agmundr', registered: '1@example.com', role: '783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> },
    { id: 24, name: 'Ford Prefect', registered: '1@example.com', role: '783783', status: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View Details</CButton>, history: <CButton component="a" color="primary" href="" variant="outline" style={{ fontSize: '12px', width: '75%' }}>View History</CButton>, select: <CFormCheck id="flexCheckDefault" /> }
]

export const fields = [
    { key: 'select', _style: { width: '10%', backgroundColor: '#c6cdcf' }, label: 'Select' },
    { key: 'id', _style: { width: '13%', backgroundColor: '#c6cdcf' }, label: 'Candidate Id' },
    { key: 'name', _style: { width: '17%', backgroundColor: '#c6cdcf' }, label: 'Candidate Name' },
    { key: 'registered', _style: { width: '18%', backgroundColor: '#c6cdcf' }, label: 'Candidate Email' },
    { key: 'role', _style: { width: '14%', backgroundColor: '#c6cdcf' }, label: 'Candidate Phone' },
    { key: 'status', _style: { width: '14%', backgroundColor: '#c6cdcf' }, label: 'View Details' },
    { key: 'history', _style: { width: '14%', backgroundColor: '#c6cdcf' }, label: 'View History' },
]
